### ISSUE TITLE
react-dom 0.15.4 fails on Node.js

### ISSUE THREAD

**Issue by gtebbutt** [cljsjs/packages#1045]
As of React 15.4.0, the minified files attempt to `require("react")` and use it if found (meaning it won't use the `cljsjs` version of React even if included in the file) - however the minified ReactDOM package expects `ReactCurrentOwner` to be found somewhere that it isn't present in the standard npm package, and crashes. 

Removing the inline code entirely and relying on the npm versions works, but if the dependencies are removed from `project.clj` the compiler fails because dependencies require the `cljsjs.react.dom` namespace.

**Comment by gtebbutt** [comment]
For anyone else with the same issue: my current workaround, using the standard npm packages, is to exclude `cljsjs/react` and `cljsjs/react-dom` from the server build, and then add the following: 
```clojure
:foreign-libs [{:file "resources/react.js"
                :provides ["cljsjs.react.dom"
                           "cljsjs.react.dom.server"]}]
```

Where `resources/react.js` just contains:
```js
var React = require("react");
var ReactDOMServer = require("react-dom/server");
```

**Comment by au-phiware** [comment]
@gtebbutt, your work-around works (thank you!), but I find it very unsatisfying... What's the correct fix for this, is it possible to create a `deps.clj` file to fix this?

**Comment by Deraen** [comment]
@au-phiware Check https://github.com/reagent-project/reagent/blob/master/CHANGELOG.md#080-alpha1-2017-07-31. Exclusions and providing mock cljsjs namespaces is no longer needed.

Not sure what the original problem was, but I think it probably is fixed in the latest Cljsjs packages, AND using Reagent alpha. Other packages (Om, Rum, Devcards, Sablono) will be updated later.
