### ISSUE TITLE
Add material-ui

### ISSUE THREAD

**Issue by johnwalker** [cljsjs/packages#232]
https://github.com/callemall/material-ui

**Comment by johnwalker** [comment]
I have a fork here:

https://github.com/johnwalker/packages/tree/material-ui/material-ui

Does this generally look right for packages? No externs yet, but I wondered if it's OK to provide the builds directly since material-ui does not provide browserified js files.

**Comment by martinklepsch** [comment]
@johnwalker hey! Usually it's best to download files directly from the authors during packaging and not store them in our repo. Is there any chance the people behind material-ui can publish builds?

In any case open a PR and lets continue discussion there :+1: 

Thanks John

**Comment by futuro** [comment]
@johnwalker One of the issues I've had trying to bundle up material-ui is that it wants to add the React source in, which should be avoided, since it clashes with the cljsjs/react package. I've opened issue callemall/material-ui#3141 to see if the MUI folks can create a browser bundle.

Alternatively, if we can sort out how to make a bundle, we could use boot to pull the source and build what we need. I just haven't figured out how to do that reliably, though I have some webpack configs that might be of help.

**Comment by Deraen** [comment]
Should be included in https://github.com/cljsjs/packages/pull/527
