### ISSUE TITLE
lein cljsbuild triggers warning for cljsjs/react

### ISSUE THREAD

**Issue by okal** [cljsjs/packages#27]
`cljsjs/react 0.12.2-5` is included as a sablono dependency

````
WARNING - Parse error. illegal use of unknown JSDoc tag "providesModule"; ignoring it
 * @providesModule warning
````

**Comment by martinklepsch** [comment]
@okal Interesting. A temporary fix would be to provide this as a compiler option:
```
:closure-warnings {:non-standard-jsdoc :off}
```
I'll try to figure out what's going on.

**Comment by swannodette** [comment]
@okal this is probably because you are using an optimization setting that is not `:advanced` or `:none`. This means Closure sees the development version of React which includes non-standard JSDoc tags. This is just an innocuous warning and I would argue there is no actual problem here. @martinklepsch's suggestion is the right one. I'm not going to add any support for foreign libraries to suppress anything as that will lead to more problems.

**Comment by okal** [comment]
@martinklepsch Thank you.
@swannodette Makes sense. It was crowding out possible actual errors from `lein cljsbuild auto test`, which is why I found it problematic.

**Comment by sickill** [comment]
@okal hey, how did you solve that eventually? I'm getting the same warning with react 0.13.1.
