### ISSUE TITLE
auth0-lock appears to be out of date

### ISSUE THREAD

**Issue by thedavidmeister** [cljsjs/packages#365]
auth0-lock currently points to version 7 of the lib but the latest major version is 8:

https://github.com/auth0/lock

**Comment by martinklepsch** [comment]
@thedavidmeister a pull request is very welcome :smile:

**Comment by DandyDev** [comment]
@martinklepsch @thedavidmeister I ran into the same problem yesterday. The current supported auth0-lock version on _cljsjs_ has styling problems in Chrome that have since then been fixed.

I'd love to make a PR, but I'm not sure how to decide which functions need to be externed (do you call it like that?). According to the original PR that added auth0-lock to this repo:

> I have provided extern definitions for all javascript functions that were documented as public.

But when I look at the [API documentation for auth0-lock](https://auth0.com/docs/libraries/lock#api), I can only see a handful of exposed/public functions.

Any hint on how to proceed, would be welcome :)

**Comment by DandyDev** [comment]
Update: after looking thoroughly at the [auth0-lock changelog](https://github.com/auth0/lock/blob/master/CHANGELOG.md) I don't see any changes in the API of auth0-lock. So if you agree, I can create a PR that updates the library itself, but keeps the current externs file.

Let me know if that's ok!

**Comment by martinklepsch** [comment]
@DandyDev feel free to do that. :+1: In case externs have changed anyways you can open another PR to do so. :)
