### ISSUE TITLE
Source file encoding (broken unicode characters)

### ISSUE THREAD

**Issue by dfrese** [cljsjs/packages#441]
Hello,

I noticed an issue, that at least the 'de' moment locale seems to be defined in sources files encoded in utf-8, which is misinterpreted as iso-latin-1 at some point. Or at least I get broken strings at the end like:

```
(println (.format (doto (js/moment "2016-03-01") (.locale "de")) "MMMM"))
;; => MÃ¤rz
```

I'm not sure who is to blame for that, but can it be solved in the cljsjs package?

David Frese

**Comment by Deraen** [comment]
1. Check the contents of outputted JavaScript files in a text editor, you should be able to find the string.
2. Check how browsers decodes the file by checking headers etc. from network log.

If the file contents are wrong in text editor, my hunch is that the cause is Closure compiler and we can't do anything about that. AFAIK ClojureScript compiler should set Unicode as default Closure output encoding, and since the latest release an option to control this has been added: https://github.com/clojure/clojurescript/blob/48cf99cc6520204dff085692803f90732ac80ba9/src/main/clojure/cljs/closure.clj#L173-L192

**Comment by dfrese** [comment]
I tracked it down:
- the moment.js file is utf-8 encoded
- without compilation (cljsbuild mode :none), goog.require loads the JS file via a <script> tag *without* a charset attribute; which falls back to the default iso chartset, or the charset set in the Content-Type header to 'text/javascript;charset=utf-8' (but http-kit does not do it by default). That's the problem.

Although setting the header in the server feels more like a workaround, than a solution to the problem; I can live with that. And even then, moment.js is to blame for creating utf-8 files (they also don't mention it in http://momentjs.com/docs/#/i18n/loading-into-browser/).

Thanks Dearaen

**Comment by Deraen** [comment]
Probably also system default locale (`LC_*`, `LANG`, and `LANGUAGE` in Unix systems, `locale` command) affect this also. Nothing we can do about this.

I have not needed to set charset for development myself, and I don't think I'm setting it for production either anywhere. My hunch is that unicode is the default for many users and I wouldn't blame anyone for using unicode in files ;)

**Comment by dfrese** [comment]
Well yes, although they did not mention that they depend on the webserver setting the encoding, for their examples to work.

Besides that, there must be a fixed standard for cljsjs/clojurescript (where utf-8 is surely the best), because other than the Javascript developer, the Clojurescript developer has no way to specify the encoding of a file directly, should it be different in certain cases - there is nothing like (:require [cljsjs.moment.locale.gr :encoding "iso-8859-7"]), or am I wrong?
