### ISSUE TITLE
no Perf addon in react-with-addons package

### ISSUE THREAD

**Issue by Gonzih** [cljsjs/packages#45]
Hi, I just updated my React dependencies from webjars to cljsjs and noticed that there is no `React.addons.Perf` anymore. Why is that? Should I include it on my own?

**Comment by martinklepsch** [comment]
@Deraen recently changed the React package to use the same extern file. I think he accidentally used the plain react one instead of the one with more addon externs. I can fix it tonight if no one else gets to it before that.

The old extern file has been deleted in this commit: https://github.com/cljsjs/packages/commit/482932d193021a8b748fccafafbc94af40d7aad3

**Comment by Deraen** [comment]
Hmh, I tried to check that there was no differences in react and react-with-addons externs before removing the other one.

https://github.com/cljsjs/packages/blob/master/react/resources/cljsjs/common/react.ext.js#L1641

**Comment by martinklepsch** [comment]
Huh. Should've checked that, sorry. 
@Gonzih what jar exactly are you depending on?

**Comment by Gonzih** [comment]
I use what is currently considered to be latest release `[cljsjs/react-with-addons "0.12.2-6"]`.

**Comment by Deraen** [comment]
@Gonzih are you still seeing this?

**Comment by Gonzih** [comment]
I did not try any releases after one i tested. I might have time to test it next week.

**Comment by Deraen** [comment]
If the problem still exists, a test case would be helpful.

**Comment by Gonzih** [comment]
ok, i will take a look at that next week then.

**Comment by martinklepsch** [comment]
Any updates available?

**Comment by futuro** [comment]
Looking at the 0.14.3-0 release, the React.addons.Perf externs are back.

**Comment by Deraen** [comment]
I presume this is fixed.
