### ISSUE TITLE
React and ReactGridLayout externs conflict

### ISSUE THREAD

**Issue by petterik** [cljsjs/packages#494]
Using `[cljsjs/react-grid-layout "0.10.8-0"]` and `[cljsjs/react "0.14.7-0"]` I'm getting this error when compiling with `:advanced` optimizations:
```javascript
SEVERE: file:/Users/petterik/.m2/repository/cljsjs/react-grid-layout/0.10.8-0/react-grid-layout-0.10.8-0.jar!/cljsjs/react-grid-layout/common/react-grid-layout.ext.js:72: 
ERROR - constant React assigned a value more than once.
Original definition at file:/Users/petterik/.m2/repository/cljsjs/react/0.14.7-0/react-0.14.7-0.jar!/cljsjs/react/common/react.ext.js:11
var React = {};
^
```
As the error says, var React is defined more than once. It's in both the cljsjs/react and cljsjs/react-grid-layout externs.

I fixed this error locally by commenting out the react assignment in the react-grid-layout externs, but I'm not sure it's the right way to solve this:
```javascript
// var React = {};
```

What's the correct way of solving this conflict?

FYI: I'm not getting this error when using the latest react - `[cljsjs/react "15.0.0-rc.2-0"]` - but I'm still interested in learning what to do here.

**Comment by Deraen** [comment]
I don't think there is other way to solve this than to remove duplicate var assignment. Looks like externs can depend on other externs on declare vars, though I'm not sure how this works as I'm not sure what is the order externs are loaded in.

As this has been fixed in recent versions (new extern doesn't refer React var), I'm going to close this.
