### ISSUE TITLE
Flag Libraries with Advanced Compilation Issues

### ISSUE THREAD

**Issue by xcthulhu** [cljsjs/packages#508]
From my own experience and others, not all libraries on CLJSJS support advanced compilation.

In particular, my own BitAuth contribution does not. This appears to be due to its use of an outdated version of [elliptic](https://github.com/indutny/elliptic) but I'm not sure).

I understand [vega](https://github.com/cljsjs/packages/tree/master/vega) may also have issues.

It would be good to note which libraries have advanced compilation issues so folks can make informed decisions before building whole apps around them only to get bitten.

**Comment by Deraen** [comment]
All libraries should work with advanced compilation, that is the idea of Cljsjs. But yes, it is possible that some packages have outdated externs. One reason is that we don't have easy way to test the externs (https://github.com/cljsjs/packages/issues/7). Some of these packages might have worked previously but have since then been updated to later version without updating the extern. When merging PRs I try to check if extern has been updated and if the version increase is likely to change the API.

I think solution is just to create an issue for each library where the advanced compilation doesn't work.

One related idea I've been thinking about, would be to flag "properly maintained" packaged somehow. Maybe list their maintainers. For example, I'm looking after React and lately also Leaflet and React-leaflet.

**Comment by martinklepsch** [comment]
I think another smoke test could be to just advanced compile *something*.
doing this we can detect if the externs are at least valid syntax.

**Comment by Deraen** [comment]
That's try. Duplicate/missing vars seem to cause some problems.

**Comment by xcthulhu** [comment]
Short of running a unit test suite, it's hard to determine if a extern file is written properly.

> All libraries should work with advanced compilation, that is the idea of Cljsjs.

In that case you should take down BitAuth, Vega, [eccjs](https://github.com/cljsjs/packages/tree/master/eccjs), and maybe attempt to audit all of the rest.

**Comment by Deraen** [comment]
Yes, proper tests are hard but we could at least detect syntax errors by loading the externs in Closure.

I think I can a Magical Bash Script to check all the externs or just changed externs in CI.

> Flagging the ones with issues might be a start, however, since developers seem to be building things around libraries only to find out rather late that they don't support advanced compilation.

Yes, flagging would be good start. Auditing all the packages is not feasible.

**Comment by Deraen** [comment]
https://circleci.com/gh/cljsjs/packages/638
https://github.com/cljsjs/packages/commit/b497a1f75159212015d3b72f25b6e9a38daf5e62

**Comment by Deraen** [comment]
All packages SHOULD work with advanced compilation, that is the reason why this project exists. If some package doesn't work, PR (or issue) should be created.
