### ISSUE TITLE
material-ui can't find ReactDOMServer

### ISSUE THREAD

**Issue by jessjohn** [cljsjs/packages#538]
<img width="804" alt="screen shot 2016-04-28 at 8 51 50 am" src="https://cloud.githubusercontent.com/assets/6101610/14886383/88c86bc6-0d1e-11e6-8d64-bba550221ad7.png">

Latest version of [material-ui](https://github.com/cljsjs/packages/tree/master/material-ui) is unable to find ReactDOMServer with [reagent](https://github.com/reagent-project/reagent).

Steps to reproduce this issue:
- `lein new figwheel hello-world -- --reagent`
- add `[cljsjs/material-ui "0.15.0-beta.2-10"]` to project.clj 
- change project.clj reagent dep to use `[reagent "0.6.0-alpha" :exclusions [cljsjs/react cljsjs/react-dom]]`
- add `cljsjs.material-ui` and `cljsjs.material-ui-svg-icons` to ns :require in core.cljs
- `cd hello-world/`
- `lein figwheel`
- then open http://localhost:3449/ in a browser, and check console.

**Comment by Deraen** [comment]
@madvas should know the best what exclusions are currently required with material-ui.

I recall from a conversation at Slack that cljsjs/react-dom should not be excluded, only cljsjs/react. Excluding cljsjs/react needs to be done differently with Reagent than with Om because Reagent doesn't directly depend on it, only through react-dom/react-dom-server.

Try a global exclusion to cljsjs/react: https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L63-L66

**Comment by madvas** [comment]
This has been solved. I've tried the instructions, got no error.

* Use the latest version `[cljsjs/material-ui "0.15.0-0"]`
* Don't put react-dom into exclusions `[reagent "0.6.0-alpha" :exclusions [cljsjs/react]]`

I may suggest using my library [cljs-react-material-ui](https://github.com/madvas/cljs-react-material-ui) for easier and more idiomatic use of `cljsjs/material-ui`
