### ISSUE TITLE
[CI] parallel builds fail

### ISSUE THREAD

**Issue by Deraen** [cljsjs/packages#754]
OpenSource CircleCI plan has 4 containers. The build currently uses 2 containers, so two builds can run parallel.

This is a problem because the CI deploy script first retrieves a list of packages to deploy (it checks all the versions against clojars), and when two PRs are merged ~at the same time, the second build sees both packages as changed and tries to deploy them. Both builds will try to deploy the same package to clojars and other fails.
- Build could use 4 containers and run no-op command on two of them...
- Some magical coordination using "HTTP mutex service"
- ...?
- Make deploy check & deploy atomic somehow? or at least check the clojars just before deploy task?

**Comment by danielcompton** [comment]
I was going to suggest using the Clojars API for this, but it's not regenerated fast enough.

2 options I have thought of:

1. At the start of deploy time, run a script which checks if there are any running builds that have a lower numbered build number than it, if so sleep for 30 seconds and try again. Something like this could be a start? 
  
  ```sh
  $ curl --silent https://circleci.com/api/v1.1/project/github/cljsjs/packages/tree/master | jq '.[] | {status, build_num}'
  ```
2. Use 3 containers in the build but make the 3rd one a no-op so that only one build at a time can be run :)

**Comment by Deraen** [comment]
@danielcompton Thanks for the idea!

This is implemented now using CircleCI API: https://github.com/cljsjs/packages/blob/master/circle.sh#L16-L25

Seems to be working:

```
Wait for previous builds to finish
Waiting for build 1203
Waiting for build 1203
Waiting for build 1203
```
