### ISSUE TITLE
[commonmark] 0.26.0 externs are wrong

### ISSUE THREAD

**Issue by sfnelson** [cljsjs/packages#810]
@edannenberg you recently updated commonmark. It looks like the generated externs you committed are missing a lot of important functionality – most of the Node methods, Events are entirely missing, even Parser.parse is missing. What's going on here?

**Comment by Deraen** [comment]
Probably the extern just can't deal with the lib. Might be good idea to rollback to the hand written extern and maybe with a note on top of the file about this. And check if 0.22 -> 0.26 has changed the API.

**Comment by sfnelson** [comment]
I've created an updated externs, I'll create a merge request now. I think @edannenberg owes me a beer...

**Comment by edannenberg** [comment]
> even Parser.parse is missing

Odd, I did test the auto generated extern with advanced compilation before creating the PR, and `Parser.parse` certainly was avail. In fact it's still running in production right now with that extern and advanced comp. enabled with zero issues, granted our use case is fairly simple though.

Just checked again via browser console and everything seems to be in order. Lots of renamed stuff `s0`, `s1` etc in autocomplete, but `commonmark.Parser` and `commonmark.Node` look untouched and are fully usable. To me it looks like the auto generated extern is actually correct.

**Comment by Deraen** [comment]
@edannenberg Looking at the generated extern which was here, it was definitely missing all methods from Node etc.

`parse` is bad test because that method is probably defined by other (maybe even built-in) externs, and all externs are global.

**Comment by edannenberg** [comment]
I'm guessing the def. of those is no longer needed for the same reasons, which is why the generator excluded them? Just checked again for `commonmark.Node.prototype.firstChild` which is not declared in the generated extern but is still untouched when using advanced compilation. Tried a few more too, also couldn't spot a single renamed function in the `commonmark` namespace via autocomplete in the browser console.

@sfnelson Did you only review the extern or did you actually run into problems with `0.26.0-0` and advanced compilation?

**Comment by Deraen** [comment]
Generator does not know anything about other externs, and should include everything. FirstChild is definitely declared by built-in externs, as there is DOM method by same name.

Also, testing commonmark object from console in adv built app does not tell if the extern is working. The foreign library code is never modified so this will work always. To test externs you need to call the methods from Cljs code. Extern is only applied to code optimized by Closure, that is, calls from Cljs code.

Extern exist so that Cljs call `(.foo js/bar)` is kept as `bar.foo()` instead of renamed to `a.b()` or such, which would not work, because foreign library would still declare `bar.foo = ...`.

**Comment by edannenberg** [comment]
I see, thanks for the clarification. Tried `Node.isContainer` from cljs code and it's indeed a problem with `0.26.0-0`. Pity the generator can't be fully trusted yet.

**Comment by sfnelson** [comment]
`isContainer` and `entering` are the two that broke our tests

**Comment by Deraen** [comment]
Regarding extern generators being trusted: work in Cljs community is currently being mostly concentrated on features that would make externs less important (Closure module processing and extern inference) instead of improving extern generators.
