### ISSUE TITLE
es5-shim

### ISSUE THREAD

**Issue by ul** [cljsjs/packages#84]
React requires [es5-shim](https://github.com/es-shims/es5-shim) to work with old browsers as stated [here](http://facebook.github.io/react/docs/working-with-the-browser.html#polyfills-needed-to-support-older-browsers). It would be nice to have the shim as cljsjs package and, may be, to add it to react deps. But I'm not sure about nuances of shim externs (it is not so ordinary lib I guess). Will anybody be so generous to package it or to take a look and highlight possible traps?

**Comment by Deraen** [comment]
I don't think foreign deps can be used to load es5-shim. It is usually loaded using IE conditional comments so that it is only loaded by clients with old browsers and this is not possible using foreign deps. 

And while loading es5-shim for all users might not break stuff (I'm not sure if they check before each polyfill if the browser already implements it) loading extra 15KB for each user is out of the question.

I would suggest just using es5-shim from [webjars](http://www.webjars.org/classic) with [ring-webjars](https://github.com/weavejester/ring-webjars).

**Comment by ul** [comment]
Sounds reasonable, thank you.
